#!/usr/bin/env python3
"""
TEMPORAL ALIGNMENT AUDIT
Strict verification of text-audio alignment in DepressoSpeech pipeline.
"""

import sys
import json
import random
import numpy as np
import pandas as pd
from pathlib import Path
from collections import defaultdict

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

SAMPLE_RATE = 16000
DATA_DIR = PROJECT_ROOT / "data" / "raw"
FEATURES_DIR = PROJECT_ROOT / "data" / "features"
SPLITS_DIR = PROJECT_ROOT / "data" / "splits"
CHUNK_META_DIR = PROJECT_ROOT / "data" / "processed" / "chunk_metadata"

DIVIDER = "=" * 72
SUBDIV  = "-" * 72


def load_transcript(csv_path, max_utterance_seconds=120.0):
    """Load transcript CSV → list of (start, end, text, confidence)."""
    df = pd.read_csv(csv_path)
    col_map = {}
    for col in df.columns:
        cl = col.strip().lower()
        if cl in ('start_time', 'start'):
            col_map['start'] = col
        elif cl in ('end_time', 'end', 'stop_time'):
            col_map['end'] = col
        elif cl in ('text', 'value', 'transcript', 'transcription', 'utterance'):
            col_map['text'] = col
        elif cl in ('confidence',):
            col_map['confidence'] = col

    segments = []
    for _, row in df.iterrows():
        start = float(row[col_map['start']])
        end = float(row[col_map['end']])
        text = str(row[col_map['text']]).strip() if pd.notna(row[col_map['text']]) else ""
        duration = end - start
        if duration <= 0 or not text:
            continue
        if duration > max_utterance_seconds:
            continue
        conf = float(row[col_map['confidence']]) if 'confidence' in col_map and pd.notna(row.get(col_map.get('confidence'))) else None
        segments.append((start, end, text, conf))
    segments.sort(key=lambda x: x[0])
    return segments


def get_audio_duration(pid):
    """Get audio duration in seconds."""
    import librosa
    audio_path = DATA_DIR / pid / f"{pid}_AUDIO.wav"
    if not audio_path.exists():
        return None
    dur = librosa.get_duration(path=str(audio_path))
    return dur


def get_sample_pids(n=5):
    """Get n random PIDs that have both audio, transcript, and features."""
    train_df = pd.read_csv(SPLITS_DIR / "train_split.csv")
    dev_df = pd.read_csv(SPLITS_DIR / "dev_split.csv")
    all_pids = [str(int(x)) for x in pd.concat([train_df, dev_df])["Participant_ID"]]

    valid = []
    for pid in all_pids:
        audio_path = DATA_DIR / pid / f"{pid}_AUDIO.wav"
        transcript_path = DATA_DIR / pid / f"{pid}_Transcript.csv"
        feature_path = FEATURES_DIR / f"{pid}_training.npz"
        if audio_path.exists() and transcript_path.exists() and feature_path.exists():
            valid.append(pid)

    random.seed(42)
    return random.sample(valid, min(n, len(valid)))


def section_header(num, title):
    print(f"\n{DIVIDER}")
    print(f"  SECTION {num}: {title}")
    print(DIVIDER)


def main():
    print(DIVIDER)
    print("  TEMPORAL ALIGNMENT AUDIT — DepressoSpeech Pipeline")
    print(f"  Date: 2026-04-13")
    print(DIVIDER)

    sample_pids = get_sample_pids(5)
    print(f"\n  Sampled PIDs: {sample_pids}")

    # ================================================================
    # SECTION 1: SEGMENT DEFINITION
    # ================================================================
    section_header(1, "SEGMENT DEFINITION")

    print("""
  TRAINING PATH segmentation:
    Method: TRANSCRIPT-BASED (variable-length utterance segments)
    Source: scripts/extract_features.py → load_transcript() → segment_audio()
    Each segment = one participant utterance from the DAIC-WOZ transcript CSV.
    Boundaries come from Start_Time / End_Time columns (in seconds).
    Audio is sliced at these exact timestamps: audio[int(start*sr) : int(end*sr)]

  INFERENCE PATH segmentation:
    Method: FIXED WINDOW (5.0s chunks, 25% overlap)
    Source: src/preprocessing/chunker.py → AudioChunker.chunk()
    Chunk duration: 5.0s → 80,000 samples @ 16kHz
    Hop:            3.75s → 60,000 samples
    Min chunk:      2.0s → 32,000 samples
    Text per chunk: generated by Whisper Base on each 5s audio chunk

  ⚠ CRITICAL: Training and Inference use DIFFERENT segmentation strategies.
""")

    print(f"  {'PID':<8} {'Segments':<10} {'Audio(s)':<12} {'Avg Seg(s)':<12} {'Min(s)':<10} {'Max(s)':<10}")
    print(f"  {'-'*8} {'-'*10} {'-'*12} {'-'*12} {'-'*10} {'-'*10}")

    pid_segments = {}
    for pid in sample_pids:
        transcript_path = DATA_DIR / pid / f"{pid}_Transcript.csv"
        segs = load_transcript(transcript_path)
        pid_segments[pid] = segs
        audio_dur = get_audio_duration(pid)
        durations = [e - s for s, e, _, _ in segs]
        avg_d = np.mean(durations) if durations else 0
        min_d = np.min(durations) if durations else 0
        max_d = np.max(durations) if durations else 0
        print(f"  {pid:<8} {len(segs):<10} {audio_dur:<12.1f} {avg_d:<12.2f} {min_d:<10.2f} {max_d:<10.2f}")

    print(f"\n  Per-sample segment boundaries (first 5 segments):")
    for pid in sample_pids:
        segs = pid_segments[pid]
        print(f"\n  PID {pid}:")
        for i, (s, e, t, c) in enumerate(segs[:5]):
            print(f"    seg[{i}]: [{s:8.2f}s, {e:8.2f}s] dur={e-s:.2f}s  text=\"{t[:50]}...\"" if len(t) > 50 else f"    seg[{i}]: [{s:8.2f}s, {e:8.2f}s] dur={e-s:.2f}s  text=\"{t}\"")

    # ================================================================
    # SECTION 2: TEXT TIMESTAMP VALIDATION
    # ================================================================
    section_header(2, "TEXT TIMESTAMP VALIDATION")

    print("""
  Text timestamp source: DAIC-WOZ Transcript CSV (pre-existing, NOT Whisper)
  Format: Start_Time, End_Time, Text, Confidence
  These timestamps are created during the DAIC-WOZ interview recording process.
  Whisper is ONLY used during inference (not training).
""")

    for pid in sample_pids:
        segs = pid_segments[pid]
        audio_dur = get_audio_duration(pid)
        print(f"\n  PID {pid} (audio={audio_dur:.1f}s, segments={len(segs)}):")

        # Check: text spills outside audio
        spills = [(s, e, t) for s, e, t, _ in segs if e > audio_dur]
        if spills:
            print(f"    ⚠ {len(spills)} segments SPILL past audio end ({audio_dur:.1f}s):")
            for s, e, t in spills[:3]:
                print(f"      [{s:.2f}s, {e:.2f}s] overshoot={e-audio_dur:.2f}s")
        else:
            print(f"    ✓ All segments within audio bounds [0, {audio_dur:.1f}s]")

        # Check: overlapping segments
        overlaps = []
        for i in range(len(segs) - 1):
            if segs[i][1] > segs[i+1][0]:
                overlaps.append((i, segs[i], segs[i+1]))
        if overlaps:
            print(f"    ⚠ {len(overlaps)} OVERLAPPING segment pairs:")
            for idx, (_, e1, _, _), (s2, _, _, _) in overlaps[:3]:
                print(f"      seg[{idx}] ends at {e1:.2f}s, seg[{idx+1}] starts at {s2:.2f}s (overlap={e1-s2:.2f}s)")
        else:
            print(f"    ✓ No overlapping segments")

        # Check: gaps between segments
        gaps = []
        for i in range(len(segs) - 1):
            gap = segs[i+1][0] - segs[i][1]
            if gap > 0:
                gaps.append((i, gap))
        if gaps:
            gap_vals = [g for _, g in gaps]
            print(f"    ℹ {len(gaps)} gaps between segments: min={min(gap_vals):.2f}s, max={max(gap_vals):.2f}s, mean={np.mean(gap_vals):.2f}s")
            # This is EXPECTED for transcript-based segments (silence between utterances)
        else:
            print(f"    ✓ No gaps (continuous segments)")

        # Print selected segments detail
        sample_indices = [0, len(segs)//4, len(segs)//2, 3*len(segs)//4, len(segs)-1]
        for idx in sample_indices:
            s, e, t, c = segs[idx]
            conf_str = f"conf={c:.4f}" if c is not None else "conf=N/A"
            print(f"    seg[{idx:3d}]: [{s:8.2f}s, {e:8.2f}s] dur={e-s:5.2f}s {conf_str}  \"{t[:60]}\"")

    # ================================================================
    # SECTION 3: AUDIO FEATURE ALIGNMENT
    # ================================================================
    section_header(3, "AUDIO FEATURE ALIGNMENT")

    print(f"""
  Audio feature extraction (TRAINING PATH):
    sampling_rate:  {SAMPLE_RATE} Hz
    frame_length:   N/A (transcript-based segments, not fixed frames)
    hop_length:     N/A (segments are variable-length utterances)

  eGeMAPS: OpenSMILE eGeMAPSv02 Functionals on each audio segment
    → Produces ONE 88-dim vector per segment (functionals = summary stats)
    → No frame-level alignment needed (it's a segment-level summary)

  MFCC: librosa 40 MFCCs + delta + delta-delta, MEANED over frames
    → Produces ONE 120-dim vector per segment (mean over time)
    → Frame-level params: n_fft=min(2048, segment_samples), default hop=512
    → No frame-level alignment needed (mean pooled to segment level)

  CRITICAL: Both audio extractors produce EXACTLY 1 feature vector per segment.
  The segment boundaries are defined by the transcript timestamps.
  Therefore, audio features are extracted from EXACTLY the same time range
  as the transcript text.
""")

    for pid in sample_pids:
        segs = pid_segments[pid]
        feature_path = FEATURES_DIR / f"{pid}_training.npz"
        data = np.load(feature_path)

        n_egemaps = data['egemaps'].shape[0]
        n_mfcc = data['mfcc'].shape[0]
        n_text = data['text_embeddings'].shape[0]
        n_segs = len(segs)

        match = (n_egemaps == n_mfcc == n_text == n_segs)
        status = "✓ ALIGNED" if match else "✗ MISALIGNED"

        print(f"  PID {pid}: {status}")
        print(f"    transcript_segments = {n_segs}")
        print(f"    egemaps.shape[0]    = {n_egemaps}")
        print(f"    mfcc.shape[0]       = {n_mfcc}")
        print(f"    text_emb.shape[0]   = {n_text}")

        if not match:
            print(f"    ⚠ COUNT MISMATCH: features do not match transcript segments!")

        # Print audio range for selected segments
        sample_indices = [0, len(segs)//2, len(segs)-1]
        for idx in sample_indices:
            s, e, t, _ = segs[idx]
            start_sample = int(s * SAMPLE_RATE)
            end_sample = int(e * SAMPLE_RATE)
            n_samples = end_sample - start_sample
            print(f"    seg[{idx:3d}]: audio_range=[{s:.2f}s, {e:.2f}s] "
                  f"samples=[{start_sample}, {end_sample}] n_frames={n_samples}")

    # ================================================================
    # SECTION 4: TEXT vs AUDIO CONSISTENCY
    # ================================================================
    section_header(4, "TEXT vs AUDIO CONSISTENCY")

    print("""
  In the TRAINING PATH, text and audio come from the SAME segment definition:
    1. Transcript CSV provides (start_time, end_time, text) per utterance
    2. Audio is sliced at [int(start*sr) : int(end*sr)]
    3. eGeMAPS/MFCC extracted from that audio slice
    4. SBERT encodes the text string from column 3

  Therefore: text_time_range == audio_time_range BY CONSTRUCTION.
  The only possible offset is integer rounding: int(time * 16000).
""")

    all_start_offsets = []
    all_end_offsets = []

    for pid in sample_pids:
        segs = pid_segments[pid]
        print(f"\n  PID {pid}:")

        for idx in [0, len(segs)//2, len(segs)-1]:
            s, e, t, _ = segs[idx]

            # Audio slicing: int(s * sr) / sr back to time
            audio_start = int(s * SAMPLE_RATE) / SAMPLE_RATE
            audio_end = int(e * SAMPLE_RATE) / SAMPLE_RATE

            offset_start = abs(s - audio_start)
            offset_end = abs(e - audio_end)

            all_start_offsets.append(offset_start)
            all_end_offsets.append(offset_end)

            flag = ""
            if offset_start > 0.1 or offset_end > 0.1:
                flag = " ⚠ FLAG: offset > 0.1s"

            print(f"    seg[{idx:3d}]: text=[{s:.4f}s, {e:.4f}s]  audio=[{audio_start:.4f}s, {audio_end:.4f}s]"
                  f"  Δstart={offset_start:.6f}s  Δend={offset_end:.6f}s{flag}")

    print(f"\n  AGGREGATE OFFSET STATISTICS:")
    print(f"    Start offsets: max={max(all_start_offsets):.6f}s, mean={np.mean(all_start_offsets):.6f}s")
    print(f"    End offsets:   max={max(all_end_offsets):.6f}s, mean={np.mean(all_end_offsets):.6f}s")
    max_offset = max(max(all_start_offsets), max(all_end_offsets))
    if max_offset > 0.1:
        print(f"    ⚠ FLAGGED: max offset {max_offset:.6f}s exceeds 0.1s threshold")
    else:
        print(f"    ✓ All offsets < 0.1s (max rounding error = 1/{SAMPLE_RATE} = {1/SAMPLE_RATE:.6f}s)")

    # ================================================================
    # SECTION 5: FEATURE-TO-TEXT MAPPING CHECK
    # ================================================================
    section_header(5, "FEATURE-TO-TEXT MAPPING CHECK")

    missing_modalities = []
    total_segments = 0

    for pid in sample_pids:
        segs = pid_segments[pid]
        feature_path = FEATURES_DIR / f"{pid}_training.npz"
        data = np.load(feature_path)

        n_segs = len(segs)
        total_segments += n_segs

        egemaps = data['egemaps']
        mfcc = data['mfcc']
        text_emb = data['text_embeddings']

        print(f"\n  PID {pid} ({n_segs} segments):")
        print(f"    text_embedding dims:  {text_emb.shape[1]} (expected 384)")
        print(f"    egemaps dims:         {egemaps.shape[1]} (expected 88)")
        print(f"    mfcc dims:            {mfcc.shape[1]} (expected 120)")

        # Check for zero/NaN rows (missing modality proxy)
        zero_egemaps = np.sum(np.all(egemaps == 0, axis=1))
        zero_mfcc = np.sum(np.all(mfcc == 0, axis=1))
        zero_text = np.sum(np.all(text_emb == 0, axis=1))
        nan_egemaps = np.sum(np.any(np.isnan(egemaps), axis=1))
        nan_mfcc = np.sum(np.any(np.isnan(mfcc), axis=1))
        nan_text = np.sum(np.any(np.isnan(text_emb), axis=1))

        if zero_egemaps > 0:
            print(f"    ⚠ {zero_egemaps} all-zero eGeMAPS rows (extraction failure fallback)")
            missing_modalities.append((pid, 'egemaps', zero_egemaps))
        if zero_mfcc > 0:
            print(f"    ⚠ {zero_mfcc} all-zero MFCC rows (extraction failure fallback)")
            missing_modalities.append((pid, 'mfcc', zero_mfcc))
        if zero_text > 0:
            print(f"    ⚠ {zero_text} all-zero text embedding rows")
            missing_modalities.append((pid, 'text', zero_text))
        if nan_egemaps > 0 or nan_mfcc > 0 or nan_text > 0:
            print(f"    ⚠ NaN values: egemaps={nan_egemaps}, mfcc={nan_mfcc}, text={nan_text}")
        if zero_egemaps == 0 and zero_mfcc == 0 and zero_text == 0 and nan_egemaps == 0 and nan_mfcc == 0 and nan_text == 0:
            print(f"    ✓ All segments have valid features for all 3 modalities")

        # Verify all have same count
        if not (egemaps.shape[0] == mfcc.shape[0] == text_emb.shape[0]):
            print(f"    ✗ SHAPE MISMATCH: egemaps={egemaps.shape[0]}, mfcc={mfcc.shape[0]}, text={text_emb.shape[0]}")

    if missing_modalities:
        print(f"\n  SUMMARY: {len(missing_modalities)} missing modality instances across {total_segments} total segments")
    else:
        print(f"\n  ✓ All {total_segments} segments across {len(sample_pids)} PIDs have complete modalities")

    # ================================================================
    # SECTION 6: EDGE CASES
    # ================================================================
    section_header(6, "EDGE CASES (CRITICAL)")

    print("\n  Checking across ALL participants in train+dev splits...\n")

    train_df = pd.read_csv(SPLITS_DIR / "train_split.csv")
    dev_df = pd.read_csv(SPLITS_DIR / "dev_split.csv")
    all_pids = [str(int(x)) for x in pd.concat([train_df, dev_df])["Participant_ID"]]

    silent_segments = 0
    very_short_segments = 0
    very_long_segments = 0
    overlapping_count = 0
    text_audio_mismatch = 0
    total_segs_all = 0
    duration_ratios = []  # track text_duration / segment_count_ratio

    for pid in all_pids:
        transcript_path = DATA_DIR / pid / f"{pid}_Transcript.csv"
        feature_path = FEATURES_DIR / f"{pid}_training.npz"
        if not transcript_path.exists() or not feature_path.exists():
            continue

        segs = load_transcript(transcript_path)
        data = np.load(feature_path)
        total_segs_all += len(segs)

        # Check for very short/long segments
        for s, e, t, _ in segs:
            dur = e - s
            if dur < 0.25:
                very_short_segments += 1
            if dur > 60:
                very_long_segments += 1

        # Check overlaps
        for i in range(len(segs) - 1):
            if segs[i][1] > segs[i+1][0]:
                overlapping_count += 1

        # Check text vs feature count mismatch
        n_text = data['text_embeddings'].shape[0]
        if n_text != len(segs):
            text_audio_mismatch += 1

        # Check silent segments (very short text for long audio)
        for s, e, t, _ in segs:
            if len(t.strip()) < 2 and (e - s) > 1.0:
                silent_segments += 1

    print(f"  Total participants checked:   {len(all_pids)}")
    print(f"  Total transcript segments:    {total_segs_all}")
    print(f"  Very short segments (<0.25s): {very_short_segments}")
    print(f"  Very long segments (>60s):    {very_long_segments}")
    print(f"  Overlapping segment pairs:    {overlapping_count}")
    print(f"  Feature count mismatches:     {text_audio_mismatch}")
    print(f"  Silent segments (short text,  {silent_segments}")
    print(f"    long audio):")

    if overlapping_count > 0:
        print(f"\n  ⚠ OVERLAPPING SEGMENTS: {overlapping_count} pairs found.")
        print(f"    This means some audio is double-counted in adjacent features.")
    else:
        print(f"\n  ✓ No overlapping segments detected.")

    if text_audio_mismatch > 0:
        print(f"  ⚠ FEATURE COUNT MISMATCH: {text_audio_mismatch} participants have different")
        print(f"    segment counts between transcript and saved NPZ features.")
    else:
        print(f"  ✓ Feature counts match transcript segments for all participants.")

    # ================================================================
    # SECTION 7: VISUAL DEBUG
    # ================================================================
    section_header(7, "VISUAL DEBUG")

    debug_pids = sample_pids[:3]

    for pid in debug_pids:
        segs = pid_segments[pid]
        audio_dur = get_audio_duration(pid)

        # Pick 3 segments: start, middle, end
        indices = [0, len(segs)//2, len(segs)-1]

        for idx in indices:
            s, e, t, c = segs[idx]
            audio_start = int(s * SAMPLE_RATE) / SAMPLE_RATE
            audio_end = int(e * SAMPLE_RATE) / SAMPLE_RATE

            print(f"\n  {SUBDIV}")
            print(f"  PID: {pid} | Segment: {idx}/{len(segs)}")
            print(f"  Segment time:    [{s:.2f}s, {e:.2f}s]  (duration: {e-s:.2f}s)")
            print(f"  Transcript:      \"{t}\"")
            conf_str = f"{c:.4f}" if c is not None else "N/A"
            print(f"  Confidence:      {conf_str}")
            print(f"  Audio sliced at: [{audio_start:.4f}s, {audio_end:.4f}s]")
            print(f"  Audio samples:   [{int(s*SAMPLE_RATE)}, {int(e*SAMPLE_RATE)}]")
            print(f"  Δstart:          {abs(s - audio_start)*1000:.3f} ms")
            print(f"  Δend:            {abs(e - audio_end)*1000:.3f} ms")

            # Sanity: does word count ~match duration?
            words = len(t.split())
            words_per_sec = words / max(e - s, 0.01)
            if words_per_sec > 10:
                print(f"  ⚠ Suspicious: {words_per_sec:.1f} words/sec (text may be too dense)")
            elif words_per_sec < 0.5 and (e - s) > 2.0:
                print(f"  ⚠ Suspicious: {words_per_sec:.1f} words/sec (possible silence/empty)")
            else:
                print(f"  ✓ Speech rate: {words_per_sec:.1f} words/sec (plausible)")
            print(f"  {SUBDIV}")

    # ================================================================
    # SECTION 8: FINAL VERDICT
    # ================================================================
    section_header(8, "FINAL VERDICT")

    print("""
  ┌────────────────────────────────────────────────────────────────────┐
  │                     ALIGNMENT ANALYSIS SUMMARY                     │
  └────────────────────────────────────────────────────────────────────┘
""")

    # Training path verdict
    print("  TRAINING PATH (transcript-based segments):")
    print("  ──────────────────────────────────────────")
    print(f"    Segmentation:    Transcript timestamps (variable-length utterances)")
    print(f"    Text source:     DAIC-WOZ Transcript CSV (Start_Time, End_Time, Text)")
    print(f"    Audio slicing:   audio[int(start*sr) : int(end*sr)]")
    print(f"    eGeMAPS:         Extracted from same audio slice → 1 vector/segment")
    print(f"    MFCC:            Extracted from same audio slice → 1 vector/segment")
    print(f"    SBERT:           Encoded from same text string   → 1 vector/segment")
    print()
    print(f"    Max rounding offset: {1/SAMPLE_RATE*1000:.4f} ms (= 1 sample at {SAMPLE_RATE}Hz)")
    print(f"    Feature count mismatches across all PIDs: {text_audio_mismatch}")
    print(f"    Overlapping segments:  {overlapping_count}")
    print()

    if text_audio_mismatch == 0 and max_offset < 0.1:
        print("    ✅ VERDICT: TEXT AND AUDIO ARE TEMPORALLY ALIGNED (TRAINING PATH)")
        print("       Text and audio share IDENTICAL segment boundaries by construction.")
        print("       The only offset is sample-level rounding (< 0.0625 ms).")
    else:
        print("    ⚠ VERDICT: ALIGNMENT ISSUES DETECTED IN TRAINING PATH")

    print()
    print("  INFERENCE PATH (fixed 5s windows):")
    print("  ─────────────────────────────────")
    print("    Segmentation:    Fixed 5.0s windows, 25% overlap (3.75s hop)")
    print("    Text source:     Whisper Base transcription of each 5s chunk")
    print("    Audio slicing:   Sliding window on VAD-filtered audio")
    print("    eGeMAPS/MFCC:    Extracted from same 5s chunk")
    print("    SBERT:           Encoded from Whisper output for same chunk")
    print()
    print("    ✅ Text and audio are aligned BY CONSTRUCTION (same chunk input)")
    print("       Whisper receives the exact audio chunk → produces text for it.")
    print("       No cross-chunk timestamp alignment needed.")

    print()
    print("  ⚠ CROSS-PATH MISMATCH (Training vs Inference):")
    print("  ───────────────────────────────────────────────")
    print("    Training: variable-length utterances (0.3s–60s+ per segment)")
    print("    Inference: fixed 5.0s windows with 25% overlap")
    print()
    print("    This means:")
    print("    1. Segment counts differ (training ~85 segs vs inference ~60 chunks)")
    print("    2. Feature distributions differ (variable vs fixed window stats)")
    print("    3. SBERT embeddings encode different text granularity")
    print("    4. Mean+std pooling (the model's input) pools over DIFFERENT")
    print("       segment definitions between training and inference")
    print()
    print("    This is the MOST CRITICAL alignment issue in the pipeline.")
    print("    It creates a TRAIN-INFERENCE DISTRIBUTION SHIFT that may")
    print("    silently degrade inference performance.")

    print(f"\n{DIVIDER}")
    print(f"  END OF TEMPORAL ALIGNMENT AUDIT")
    print(f"{DIVIDER}")


if __name__ == "__main__":
    main()
